version: CI Build {Build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform:
- x86
- x64
before_build:
- cmd: 'echo #define NSUDO_CI_BUILD L"(CI Build %APPVEYOR_BUILD_NUMBER%)" >> %APPVEYOR_BUILD_FOLDER%\NSudo\CIBuild.h'
build:
  project: NSudo.sln
  verbosity: normal
after_build:
- cmd: >-
    7z a -r NSudo_%APPVEYOR_BUILD_VERSION%_%PLATFORM%_%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%\Output\Binary\*.exe

    7z a -r NSudo_%APPVEYOR_BUILD_VERSION%_%PLATFORM%_%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%\Output\Binary\*.pdb

    7z a -r NSudo_%APPVEYOR_BUILD_VERSION%_%PLATFORM%_%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%\Output\Binary\*.json
artifacts:
- path: NSudo_%APPVEYOR_BUILD_VERSION%_%PLATFORM%_%CONFIGURATION%.zip
