version: 4.4.1705.{Build}
image: Visual Studio 2017
configuration: Release
platform:
- x86
- x64
install:
- cmd: >-
    git submodule init

    git submodule update --recursive
build:
  project: NSudo.sln
  verbosity: normal
after_build:
- cmd: >-
    7z a -mx9 -r release.7z *.dll

    7z a -mx9 -r release.7z *.exe