version: CI Build {Build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform:
- x86
- x64
before_build:
- cmd: 'echo #define NSUDO_CI_BUILD L"(CI Build %APPVEYOR_BUILD_NUMBER%)" >> %APPVEYOR_BUILD_FOLDER%\NSudoSDK\CIBuild.h'
build:
  project: NSudo.sln
  verbosity: normal
after_build:
- cmd: >-
    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\Output\Binary\*.exe

    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\Output\Binary\*.pdb

    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\Output\Binary\*.json
artifacts:
- path: NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip
environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: 4ZHCSC8j97Qg0prnX1chpbJHMpO8xdguT0/YbeyL6RTRuo4PLhi5sOA07CIu+oxM
