version: CI Build {Build}
image: Visual Studio 2017
configuration:
- Debug - NSudo CUI - Subsystem Console
- Debug - NSudo CUI - Subsystem Windows
- Debug - NSudo GUI - Subsystem Windows
- Release - NSudo CUI - Subsystem Console
- Release - NSudo CUI - Subsystem Windows
- Release - NSudo GUI - Subsystem Windows
platform:
- x86
- x64
before_build:
- cmd: 'echo #define NSUDO_CI_BUILD L"(CI Build %APPVEYOR_BUILD_NUMBER%)" >> %APPVEYOR_BUILD_FOLDER%\NSudoSDK\CIBuild.h'
build:
  project: NSudo.sln
  verbosity: normal
after_build:
- cmd: >-
    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\Output\*.exe

    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\Output\*.pdb

    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\Output\*.json
artifacts:
- path: NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip
